"""
Django settings for servicyee_backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$xcdq%&^3paqw%%-qgsqwp(m1i98h&9h)m&bc$2su#xj0jx7uz"

# SECURITY WARNING: don't run with debug turned on in production!
env = environ.Env(
    DEBUG=(bool, True),
    SECRET_KEY=(
        str,
        "django-insecure-$xcdq%&^3paqw%%-qgsqwp(m1i98h&9h)m&bc$2su#xj0jx7uz",
    ),
    ALLOWED_HOSTS=(list, ["localhost", "127.0.0.1"]),
    DATABASE_URL=(str, "sqlite:///db.sqlite3"),
    # Keycloak settings with defaults for development
    KEYCLOAK_SERVER_URL=(str, "http://localhost:8080"),
    KEYCLOAK_REALM=(str, "master"),
    KEYCLOAK_CLIENT_ID=(str, "django-app"),
    KEYCLOAK_CLIENT_SECRET_KEY=(str, "dummy-secret"),
    KEYCLOAK_CACHE_TTL=(int, 300),
    KEYCLOAK_LOCAL_DECODE=(str, "False"),
    KEYCLOAK_MASTER_REALM=(str, "master"),
    KEYCLOAK_ADMIN_CLIENT_ID=(str, "admin-cli"),
    KEYCLOAK_ADMIN_USERNAME=(str, "admin"),
    KEYCLOAK_ADMIN_PASSWORD=(str, "admin"),
    KEYCLOAK_ADMIN_CLIENT_SECRET=(str, "dummy-admin-secret"),
)

# Try to read .env file if it exists
env_file = os.path.join(BASE_DIR, ".env")
if os.path.exists(env_file):
    environ.Env.read_env(env_file)

DEBUG = env("DEBUG")
SECRET_KEY = env("SECRET_KEY")
ALLOWED_HOSTS = ['*']

DATABASES = {
    "default": env.db(),  # reads DATABASE_URL from .env
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "user",
    "base",
    "rest_framework",
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_keycloak_auth.middleware.KeycloakMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "keycloak_auth.backends.KeycloakAuthenticationCodeBackend",
    "django.contrib.auth.backends.ModelBackend",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


KEYCLOAK_EXEMPT_URIS = []
KEYCLOAK_CONFIG = {
    "KEYCLOAK_SERVER_URL": env("KEYCLOAK_SERVER_URL"),
    "KEYCLOAK_REALM": env("KEYCLOAK_REALM"),
    "KEYCLOAK_CLIENT_ID": env("KEYCLOAK_CLIENT_ID"),
    "KEYCLOAK_CLIENT_SECRET_KEY": env("KEYCLOAK_CLIENT_SECRET_KEY"),
    "KEYCLOAK_CACHE_TTL": int(env("KEYCLOAK_CACHE_TTL")),
    "LOCAL_DECODE": env("KEYCLOAK_LOCAL_DECODE") == "True",
}

KEYCLOAK_SERVER_URL = env("KEYCLOAK_SERVER_URL")
MASTER_REALM = env("KEYCLOAK_MASTER_REALM")
KEYCLOAK_REALM = env("KEYCLOAK_REALM")
KEYCLOAK_ADMIN_CLIENT_ID = env("KEYCLOAK_ADMIN_CLIENT_ID")
KEYCLOAK_ADMIN_USERNAME = env("KEYCLOAK_ADMIN_USERNAME")
KEYCLOAK_ADMIN_PASSWORD = env("KEYCLOAK_ADMIN_PASSWORD")
KEYCLOAK_ADMIN_CLIENT_SECRET = env("KEYCLOAK_ADMIN_CLIENT_SECRET")
KEYCLOAK_CLIENT_ID = env("KEYCLOAK_CLIENT_ID")
